# Data path. adjust them!
common:
    image_file: "/media/sdcard/li_cam_calib/image/0.png"
    pcd_file: "/media/sdcard/li_cam_calib/pcd/0.pcd"
    result_file: "/media/sdcard/li_cam_calib/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [1263.207, 0.0,      945.461,
                0.0,     1263.735,  550.832,
                0.0,     0.0,      1.0     ]
    dist_coeffs: [0.05311, -0.11528, 0.00272, -0.00312, 0.10370]

# Calibration Parameters.!
calib:
    calib_config_file: "/media/sdcard/li_cam_calib/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
